# Generated by Django 4.2.7 on 2023-11-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factor_empaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_de_empaque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('inventario', models.IntegerField(default=0)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ManyToManyField(blank=True, to='productos.categoria')),
                ('empresa_proveedor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='perfil.empresaproveedor')),
                ('factor_de_empaque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.factor_empaque')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('producto_a_pedir', models.OneToOneField(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Pedido de Producto',
                'verbose_name_plural': 'Pedidos de Productos',
            },
        ),
    ]
